apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sc-strapi
  namespace: ns-strapi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: sc-strapi